# Generated by Django 4.1.1 on 2022-09-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cteated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
